# ============================================================
# SELECTED SYMBOLS
# ============================================================

SELECTED_SYMBOLS = [
    "QQQ",
    "SPY",
    "SOXX",
    "IBM",
    "MSFT",
    "PLTR",
    "CRWV",
    "APP",
    "DRAM",
    "SKHY",
    "NBIS",
    "COHR",
    "POET",
    "AMAT",
    "GEMI",
    "JD",
    "BLSH",
    "SNDK",
    "NVTS",
    "VST",
    "IREN",
    "OKLO",
    "ENPH",
    "RKLB",
    "FLY",
    "LUNR",
    "CRCL",
    "SPCX",
    "CBRS",
    "EWZ",
    "EWY",
    "REMX",
    "GOLD",
    "META",
    "UBER",
    "TSLA",
]
