# ============================================================
# SELECTED SYMBOLS
# ============================================================

SELECTED_SYMBOLS = [
    "DKNG",
    "AVGO",
    "NVDA",
    "MRVL",
    "ASTS",
    "NBIS",
    "PL",
    "DRAM",
    "SKHY",
    "CRDO",
    "POET",
    "CBRS",
    "NVTS",
    "VST",
    "IREN",
    "OKLO",
    "ORCL",
    "RKLB",
    "FLY",
    "LUNR",
    "CRCL",
    "SPCX",
    "EWZ",
    "EWY",
    "REMX",
    "MSTR",
    "META",
    "UBER",
    "MSFT",
    "TSLA",
]
